questions =  [
    {"id": 0, "question": "I have actively participated in a protest.", "effects": {"right": 1}},
    {"id": 1, "question": "I have persuasive discussions with friends, family, and social media users.", "effects": {"right": 1}},
    {"id": 2, "question": "I have an active membership and/or attend meetings for an activist organization.", "effects": {"right": 1}},
    {"id": 3, "question": "I have ended friendships over differences in political opinion.", "effects": {"right": 1}},
    {"id": 4, "question": "I have read recently published literature (last 20 years) that engages with a political topic that I find significant.", "effects": {"right": 1}},
    {"id": 5, "question": "I am a vegan.", "effects": {"right": 1}},
    {"id": 6, "question": "I do not buy fast fashion.", "effects": {"right": 1}},
    {"id": 7, "question": "I am celibate for political reasons.", "effects": {"right": 1}},
    {"id": 8, "question": "I have participated in a boycott of a major corporation (e.g. Target, Amazon, Walmart).", "effects": {"right": 1}},
    {"id": 9, "question": "I have called out a close friend for a flaw in their ideology in a public forum.", "effects": {"right": 1}},
    {"id": 10, "question": "Most of my activism is online.", "effects": {"right": -1}},
    {"id": 11, "question": "I am able to be close with people, even when they disagree with my beliefs fundamentally.", "effects": {"right": -1}},
    {"id": 12, "question": "I have never broken a law or rule on behalf of my beliefs.", "effects": {"right": -1}},
    {"id": 13, "question": "I do not break social harmony for the sake of discussions regarding my beliefs.", "effects": {"right": -1}},
    {"id": 14, "question": "I did not vote in the last general election (while being of age).", "effects": {"right": -1}},
    {"id": 15, "question": "I believe that it is important to concede on some of your beliefs in a situation where it is impractical to cause an argument.", "effects": {"right": -1}},
    {"id": 16, "question": "I do not resist authority if it will be to my detriment.", "effects": {"right": -1}},
    {"id": 17, "question": "I feel strongly about issues that do not personally affect me.", "effects": {"auth": 1}},
    {"id": 18, "question": "I have volunteered at a homeless shelter outside of any external benefit (school/organizational requirements, resume credit, money, etc.).", "effects": {"auth": 1}},
    {"id": 19, "question": "I am sympathetic towards people who disagree with me on topics that affect them.", "effects": {"auth": 1}},
    {"id": 20, "question": "I actively participate in civil rights organizations for minorities that I am not a part of.", "effects": {"auth": 1}},
    {"id": 21, "question": "I will support an organization that disagrees with some of my beliefs if they are otherwise contributing a net positive to society.", "effects": {"auth": 1}},
    {"id": 22, "question": "I appeal to classical arguments from literature I have read over morals or empathy when constructing an argument.", "effects": {"auth": -1}},
    {"id": 23, "question": "I became convinced of my current political beliefs because of something that happened in my life.", "effects": {"auth": -1}},
    {"id": 24, "question": "I care about children's rights.", "effects": {"auth": 1}},
    {"id": 25, "question": "I am a registered organ donor.", "effects": {"auth": 1}},
    {"id": 26, "question": "I have donated or volunteered for a cause anonymously.", "effects": {"auth": 1}},
    {"id": 27, "question": "I have voted on legislation that has nothing to do with me.", "effects": {"auth": 1}},
    {"id": 28, "question": "I care about non-human rights.", "effects": {"auth": 1}},
    {"id": 29, "question": "I find the practical more important than the principle.", "effects": {"auth": -1}},
    {"id": 30, "question": "The issues that I care about the most are the ones close to home.", "effects": {"auth": -1}},
    {"id": 31, "question": "Just because a belief is logically sound, doesn't mean that it is practical to enforce in society.", "effects": {"auth": -2}},
    {"id": 32, "question": "My strongest political beliefs are economic more than social.", "effects": {"auth": -1}},
    {"id": 33, "question": "Beliefs should be based on universal logic and not people's feelings.", "effects": {"auth": -1}},
    {"id": 34, "question": "No legislation passed in the name of progressivism should infringe on my natural rights.", "effects": {"auth": -1}},
    {"id": 35, "question": "People who disagree with me are irrational.", "effects": {"auth": -1}},
];
